# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deployment_tp/payload.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x64\x65ployment_tp/payload.proto\"}\n\x17\x44ockerDeploymentPayload\x12/\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x1f.DockerDeploymentPayload.Action\x12\r\n\x05image\x18\x02 \x01(\t\"\"\n\x06\x41\x63tion\x12\n\n\x06\x44\x45PLOY\x10\x00\x12\x0c\n\x08UNDEPLOY\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deployment_tp.payload_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DOCKERDEPLOYMENTPAYLOAD._serialized_start=31
  _DOCKERDEPLOYMENTPAYLOAD._serialized_end=156
  _DOCKERDEPLOYMENTPAYLOAD_ACTION._serialized_start=122
  _DOCKERDEPLOYMENTPAYLOAD_ACTION._serialized_end=156
# @@protoc_insertion_point(module_scope)
